{{- if .Values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-openim" .Release.Name }}
  labels:
    {{- include "openim.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.clusterRole.rules | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-openim" .Release.Name }}
  labels:
    {{- include "openim.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.clusterRole.serviceAccountName }}
    namespace: {{ include "openim.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-openim" .Release.Name }}
{{- end }}
